# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = """
[](fg:#30303a)\
${custom.os}\
[](fg:#30303a bg:#212428)\
$directory\
[](fg:#212428 bg:#30303a)\
$git_branch\
$git_status\
[ ](fg:#30303a)\
$fill\
$cmd_duration$jobs$memory_usage
$character\
"""

[fill]
style = "bold fg:#30303a"
symbol = ""

[custom.os]
when = true
symbol = "󰀵 "
style = "bg:#30303a"
format = "[ $symbol]($style)"
 
[directory]
truncation_length = 3
truncation_symbol = "…/"
style = "bg:#212428 fg:#89dceb"
format = "[ $path ]($style)"
 
[git_branch]
symbol = "󰘬"
style = "bg:#30303a"
format = '[[ $symbol $branch ](bg:#30303a fg:#37d99e)]($style)'
 
[git_status]
style = "bg:#30303a"
format = '[[($all_status$ahead_behind )](bg:#30303a fg:#37d99e)]($style)'

[cmd_duration]
min_time = 0
style = "yellow"
format = "[   $duration]($style)"

[jobs]
symbol_threshold = 1
number_threshold = 1
symbol = " "
style = "bg:#30303a"
format = "[ $symbol$number]($style)"

[memory_usage]
disabled = false
threshold = 0
symbol = " "
style = "bold dimmed white bg:#30303a"
format = " [](fg:#30303a)[$symbol$ram_pct]($style)[](fg:#30303a)"

[character]
success_symbol = "[󱞩](bold green)"
error_symbol = "[󱞩](bold red)"
vimcmd_symbol = "[󱞩](bold cyan)"
format = " $symbol "
