# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = """
[](fg:#30303a)\
${custom.os}\
[](fg:#30303a bg:#212428)\
$directory\
[](fg:#212428 bg:#30303a)\
$git_branch\
$git_status\
[ ](fg:#30303a)\
"""

[custom.os]
when = true
symbol = "󰀵 "
style = "bg:#30303a white"
format = "[ $symbol]($style)"

[directory]
truncation_length = 3
truncation_symbol = "…/"
style = "bg:#212428 cyan"
format = "[ $path ]($style)"
 
[git_branch]
symbol = "󰘬"
style = "bg:#30303a"
format = '[[ $symbol $branch ](bg:#30303a fg:#37d99e)]($style)'
 
[git_status]
style = "bg:#30303a"
format = '[[($all_status$ahead_behind )](bg:#30303a fg:#37d99e)]($style)'
