# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = """
[](#191d22)\
$username\
[](bg:#212428 fg:#191d22)\
$directory\
[](fg:#212428 bg:#33363a)\
$git_branch\
$git_status\
[](fg:#33363a bg:#3e4145)\
$time\
[ ](fg:#3e4145)\
"""
 
# Disable the blank line at the start of the prompt
# add_newline = false
 
# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#191d22"
style_root = "bg:#191d22"
format = '[ $user ]($style)'
 
[directory]
style = "bg:#212428"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
 
# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "📄 "
"Downloads" = "📥 "
"Music" = "🎜 "
"Pictures" = "📷 "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[git_branch]
symbol = ""
style = "bg:#33363a"
format = '[[ $symbol $branch ](bg:#33363a)]($style)'
 
[git_status]
style = "bg:#33363a"
format = '[[($all_status$ahead_behind )](bg:#33363a)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#3e4145"
format = '[ [$time ](bg:#3e4145)]($style)'

