# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = """
$directory\
$git_branch\
$git_status\
[ ](fg:#313244)\
"""

[custom.os]
when = true
symbol = " 󰀵 "
style = "bg:#313244 white"
format = "[$symbol]($style)"

[directory]
truncation_length = 3
truncation_symbol = "…/"
style = "bg:#25282c cyan"
format = "[ $path ]($style)"
 
[git_branch]
symbol = "󰘬"
style = "bg:#313244"
format = '[[ $symbol $branch ](bg:#313244 green)]($style)'
 
[git_status]
style = "bg:#313244"
format = '[[($all_status$ahead_behind )](bg:#313244 green)]($style)'
