# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = """
[](#212428)\
$directory\
[](fg:#212428 bg:#30303a)\
$git_branch\
$git_status\
[ ](fg:#30303a)\
"""
 
# Disable the blank line at the start of the prompt
# add_newline = false
 
[directory]
style = "bg:#212428 fg:#50cad2"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
 
[git_branch]
symbol = "󰘬"
style = "bg:#30303a"
format = '[[ $symbol $branch ](bg:#30303a fg:#37d99e)]($style)'
 
[git_status]
style = "bg:#30303a"
format = '[[($all_status$ahead_behind )](bg:#30303a fg:#37d99e)]($style)'
